I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script call
    call prologue from _call_prologue
  File "game/prologue.rpy", line 102, in script
    $g(dot_mozi("「当機は貴方のスマートフォンです。モノノベシゲト様」"))
  File "game/prologue.rpy", line 102, in <module>
    $g(dot_mozi("「当機は貴方のスマートフォンです。モノノベシゲト様」"))
OSError: Couldn't find file 'game/audio/bg1.ogg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 8, in script call
    call prologue from _call_prologue
  File "game/prologue.rpy", line 102, in script
    $g(dot_mozi("「当機は貴方のスマートフォンです。モノノベシゲト様」"))
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/prologue.rpy", line 102, in <module>
    $g(dot_mozi("「当機は貴方のスマートフォンです。モノノベシゲト様」"))
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 4379, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1224, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1202, in periodic_thread_main
    periodic_pass()
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1144, in periodic_pass
    c.periodic()
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 534, in periodic
    topf = load(filename)
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\loader.py", line 833, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'game/audio/bg1.ogg'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
擬人家電 1.0
Mon Jan 29 14:34:08 2024
